name: 02-workflow-event
on:
    # push:
    # pull_request:
     workflow_dispatch:
    # schedule:
    #    - cron: '*/5 * * * *'
    

   
jobs:
    echo-event:
        runs-on: ubuntu-latest
        steps:
            - name: event type
              run: echo "print the event name ${{github.event_name}}"
    
